steps:
  #Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/<gcp_project>/gcp-compute-resource-reporting/gcp-compute-resource-reporting',
        '.'
      ]

  #Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/<gcp_project>/gcp-compute-resource-reporting/gcp-compute-resource-reporting'
      ]

  #Update Cloud Run job with new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'jobs', 'update', 'gcp-compute-resource-reporting',
        '--image', 'us-central1-docker.pkg.dev/<gcp_project>/gcp-compute-resource-reporting/gcp-compute-resource-reporting',
        '--region', 'us-central1'
      ]

images:
  - 'us-central1-docker.pkg.dev/<gcp_project>/gcp-compute-resource-reporting/gcp-compute-resource-reporting'
